- name: Create Node Exporter user
  user:
    name: node_exporter
    system: yes
    createhome: no
    shell: /bin/false

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"
    mode: '0755'

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/opt/node_exporter"
    remote_src: yes
    creates: "/opt/node_exporter/node_exporter"

- name: Install Node Exporter binary
  copy:
    src: "/opt/node_exporter/node_exporter-1.6.1.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'

- name: Setup Node Exporter service
  template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"

- name: Enable and start Node Exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started
  become: yes

- name: Update Node Exporter configuration
  template:
    src: node_exporter_config.j2
    dest: /etc/node_exporter/config.yml
  notify: restart node_exporter

- name: Clean up installation files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/node_exporter.tar.gz"
    - "/opt/node_exporter"
